[package]
# `name = "blake3"` is a bit confusing, because that's the same as the official
# Rust implementation that this is wrapping. However, this crate doesn't get
# published to crates.io. Instead, it gets packaged by Maturin and published on
# PyPI. Installing this with `pip install blake3` is better than something
# redundant like `pip install PyBLAKE3-py`.
name = "blake3"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
c = ["blake3/c"]

[dependencies]
blake3 = "0.2.2"
pyo3 = { version = "0.9.0-alpha.1", features = ["extension-module"] }
