[package]
name = "blake3-py"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[lib]
name = "blake3"
crate-type = ["cdylib"]

[features]
c = ["blake3/c"]

[dependencies]
blake3 = "0.2.2"
pyo3 = { version = "0.9.0-alpha.1", features = ["extension-module"] }
